packages:
  - packages/**
  - docs
  - integration-tests/**
  - demo/*
catalogs:
  react18:
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.7
    react: 19.1.1
    react-dom: 19.1.1
catalog:
  "better-call": "1.0.15"
  "@better-fetch/fetch": "^1.1.18"
  "unbuild": "^3.6.1"
  "typescript": "^5.9.2"
  "vitest": "^3.2.4"